env:
  nodeEnv: production
  pgSslMode: require
  devExposeTokens: "false"

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1024Mi

networkPolicy:
  enabled: true
